### ISSUE TITLE
rename: command not found

### ISSUE THREAD

**Issue by OndroV** [Saskia-Oosterbroek/decona#13]
Hi, it looks like package "rename" is not included in the installation.
I got the following message from a relatively fresh installation of Ubuntu 18.04 , and miniconda updated to 4.10.1.
`/path/to/decona: line 268: rename: command not found`

**Comment by givdieri** [comment]
> 
> 
> Hi, it looks like package "rename" is not included in the installation.
> I got the following message from a relatively fresh installation of Ubuntu 18.04 , and miniconda updated to 4.10.1.
> `/path/to/decona: line 268: rename: command not found`

Hi, I'm getting the same warning message, installed about 2 weeks ago on Ubuntu.

**Comment by ordynets** [comment]
Hi all,
I also had this issue on Ubuntu 20.04 working as WSL (Windows Subsystem for Linux). 
It was fixed by manual installation of the `rename` :
`sudo apt install rename`
(as advised by paweljvn at https://askubuntu.com/questions/1095759/rename-command-not-found-when-running-a-script)
