### ISSUE TITLE
Primer trimming

### ISSUE THREAD

**Issue by thierryjanssens** [Saskia-Oosterbroek/decona#20]
Hello Saskia,

in which step did you include the step for removal of primer sequences? If any.

kind regards,

Thierry

**Comment by Saskia-Oosterbroek** [comment]
Hi Thierry,

At this moment primer removal is not incorporated. If you use the demultiplex option barcodes+adapters are removed by qcat. However qcat is still working, it has been archived and it's support discontinued. I actually recommend demultiplexing with Guppy. Removal of primer sequences has worked well for me with Cutadapt (https://cutadapt.readthedocs.io/en/stable/guide.html).

Best,
Saskia
