### ISSUE TITLE
Can't find decona command/ installation issue

### ISSUE THREAD

**Issue by juanboja** [Saskia-Oosterbroek/decona#21]
Hi Saskai,

I have installed decona on a linux machine with Ubuntu using Conda 4.11 following the detailed instructions. However, after activating  deconda environment the following error message appears when I run the command `decona -d -l 800 -m 1200 -q 10 -c 0.80 -n 100 -M` :

decona: command not found

I am sure I must be missing something and any advice would be greatly appreciated.

Thanks,

Julio

**Comment by Saskia-Oosterbroek** [comment]
Hi Julio,

There might be an issue with the installer file, which I don't think includes conda 4.11. 
You can try copying the files from the .tar file yourself (which is basically what the installer script does). When you extract the tar file you should end up with a few folders amongst which a `decona/bin/` folder. The files in that folder should be moved to your conda environment bin/. 

You can run `conda env list` to find out where your Decona environment is located. Usually something like: `/home/user/conda/envs/decona`. There you should also be able to find your bin: ` /home/user/conda/envs/decona/bin`. 

Copying them should be straight forward:
`cp location_of_unpacked_tar/decona/bin/*  /home/user/conda/envs/decona/bin`

Let me know it this works,
Saskia

**Comment by juanboja** [comment]
Thank you Saskia, it worked! I can use decona now.
