### ISSUE TITLE
awk: run time error with combined2.txt

### ISSUE THREAD

**Issue by thierryjanssens** [Saskia-Oosterbroek/decona#23]
Hi Saskia,

in a decona run on a limited sample set I have encountered the following error. 

decona -T 8 -f -l 500 -q 10 -c 0.80 -n 10 -i -r -g 1 -M > decona.log

It stumbles (before even starting the re-clustering):

...
[16:47:54 - Stitch] Processing aede1ed7-eb82-4cd8-9860-6dd2cf77a887:0-.
[16:47:54 - Stitch] Used heuristic 0 times for aede1ed7-eb82-4cd8-9860-6dd2cf77a887:0-.
awk: run time error: not enough arguments passed to sprintf("%d (%.2f%)")
        FILENAME="combined2.txt" FNR=1 NR=1

**Comment by Saskia-Oosterbroek** [comment]
Hello Thierry,

Thanks for reporting! This is a known bug associated with empty files and should be resolved in the next release.

**Comment by thierryjanssens** [comment]
Looking forward to the new version!
Do you have any plans for a snakemake workflow of your pipeline or collaboration  in this?

**Comment by Robvh-git** [comment]
Hi Thierry, 

see https://github.com/Saskia-Oosterbroek/decona/issues/39 for fix.
