### ISSUE TITLE
Result only on one barcode

### ISSUE THREAD

**Issue by Kata-Pa** [Saskia-Oosterbroek/decona#24]
Hi Saskia!

First of all, thank you for this useful and fast tool for Nanopore amplicon data analysis. I had two eDNA samples run on Minion and I got the results as fastq files in two folders, one for each barcode, so folder barcode01 and barcode02. I have run the decona command in /home/user/eDNA where these two folders are (so /home/user/eDNA/barcode01 and /home/user/eDNA/barcode02), using the -f parameter. Everything went well and decona completed the job with no errors. I got a folder named data and in there there is the folder "barcode01_concatenated", the folder "result" which only contains results on barcode01 and the file "percentage_per_barcode" which again only has information on barcode01. Should I have run decona from a different directory and which would that be? 
Thank you in advance!
/Katerina

**Comment by Saskia-Oosterbroek** [comment]
Hi Katerina,

Where you able to find out what went wrong? It seems to me like it should have worked..

Saskia
