### ISSUE TITLE
Option -T is ignored: multi-threading with OpenMP is NOT enabled!

### ISSUE THREAD

**Issue by MMAThijssen** [Saskia-Oosterbroek/decona#28]
Hi, 

When I run Decona with -T 4, the error message 'Option -T is ignored: multi-threading with OpenMP is NOT enabled!' is given. I suspect this to be something with cd-hit-est. I tried explicitly exporting OMP_NUM_THREADS=4, but the issue remained. Do you know how this can be solved?

**Comment by Saskia-Oosterbroek** [comment]
Hello,

Yes, it has to do with the installation of CD-hit, in the standard version you get through Bioconda it does not seem to be included. If you install via the instructions on their Github it should work: https://github.com/weizhongli/cdhit/wiki/2.-Installation

**Comment by jhgffhgjf** [comment]
hello, I have the same problem, but i cant figure out how to make it work. Do i install the CD-hit program in a seperate conda environment, or do i copy paste the contents of CD- hit into the bin of decona?

**Comment by MMAThijssen** [comment]
Thank you for your response! The use of the CD hit version from their GitHub gave me some other errors. Therefore I decided to use the bioconda version as this is not the most time consuming step.
