### ISSUE TITLE
Medaka accepts no thead limit

### ISSUE THREAD

**Issue by joran520** [Saskia-Oosterbroek/decona#4]
Dear Ms. Oosterbroek

I have used you script with the -T option set to 20.
As it reaches the medaka consensus step it uses over 60 threads on our server causing lags and craches.
Is it possible to set the thread limiter in all steps?

With kind regards
Joran Vanhollebeke

**Comment by Saskia-Oosterbroek** [comment]
Dear Joran, 

Thank you for pointing out this issue, this is quite a big problem! I have had some more notifications about unexpected behaviour of the multi-threading option, but rather that it didn't work, too many threads is new for me. I will look into it in the next week or so and hope to release an update soon, in version 0.1.3 this problem should be solved. 

Kind regards,
Saskia
