### ISSUE TITLE
Make blast db not working?

### ISSUE THREAD

**Issue by ap1438** [Saskia-Oosterbroek/decona#41]
decona -l 800 -m 2100 -q 10 -c 0.80 -n 100 -M -B ../../Database/Decona/SILVA/SILVA_138.1_SSURef_tax_silva.fasta 

Building a new DB, current time: 05/25/2022 19:25:20
New DB name:   /mnt/USB2/group_gs/Akash/Nanopore/Database/Decona/SILVA/SILVA_138.1_SSURef_tax_silva.fasta
New DB title:  ../../Database/Decona/SILVA/SILVA_138.1_SSURef_tax_silva.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File ../../Database/Decona/SILVA/SILVA_138.1_SSURef_tax_silva.fasta does not exist

IT is not making blast DB.
I installed Blast plus in conda env of decona from conda.

**Comment by Robvh-git** [comment]
Hello,

I think that the issue is that when you use the ```-B``` option, the .fasta file has to be within the directory of your data. Then decona will make a blastdb from this fasta file and store it in a new folder "BLASTdatabase".

So to fix it: copy your file "SILVA_138.1_SSURef_tax_silva.fasta" into the directory where your data is, and run following command:

```decona -l 800 -m 2100 -q 10 -c 0.80 -n 100 -M -B SILVA_138.1_SSURef_tax_silva.fasta```

This will probably fix your issue

**Comment by ap1438** [comment]
Thank you

**Comment by neenah13** [comment]
Hey, I had the same issue and Robvh-git's comment solved it for me. Blast database is getting created but the issue i am facing is that the results folder has 3 folders namely Medaka,Racon and reclustered but they are empty. Also, can u tell me how you installed blast in the conda environment?. I am new to bioinformatics.

**Comment by ap1438** [comment]
Hi neenah13,
I cannot help you in the issue of empty folders. But, what you can do is as follows-
Activate conda environment using conda activate decona.
Then install bcftools using the given conda code-conda install -c bioconda/label/broken bcftools                                     
(source-https://anaconda.org/bioconda/bcftools,Code no-2)
Then install blast using the code-conda install -c bioconda blast
(Source-https://anaconda.org/bioconda/blast,Code no-1)

Use this SILVA DATABASE link to download SILVA 16s rRNA Databse
https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_138.1_SSURef_tax_silva.fasta.gz
Then unzip it using tar -xvzf SILVA_138.1_SSURef_tax_silva.fasta.gz
And Place the query file and the SILVA databse file in the same folder and run the command.

Please do the needful and check if its working or not.
Thanks

**Comment by neenah13** [comment]
> > Hey, I had the same issue and Robvh-git's comment solved it for me. Blast database is getting created but the issue i am facing is that the results folder has 3 folders namely Medaka,Racon and reclustered but they are empty. Also, can u tell me how you installed blast in the conda environment?. I am new to bioinformatics.
> 
> Hi @neenah13, could you post the exact decona command you run in the terminal?

Hello, this was the command i used - 
decona -l 700 -m 1700 -q 10 -c 0.99 -n 100 -i -r -M -B SILVA_138.1_SSU_tax_silva.fasta

**Comment by neenah13** [comment]
Hello, thank you sooo much for reaching out to me. My conda environment of
decona has both of these - bcftools and blast. I tried running decona with
only 1 sample and it works beautifully. How do i make it run on all my 12
samples?.

My command for 1 sample is as follows -
decona -d -l 700 -m 1700 -q 10 -c 0.80 -n 50 -i -r -M -B
SILVA_138.1_SSURef_tax_silva.fasta

**Comment by neenah13** [comment]
Hello, i finally figured it out. This is for anybody struggling with understanding how to make it work. This is how i did it - put 1 sample in a folder. This folder along with SILVA fasta file in a folder and run decona command from within this directory. 
Example - folder name Trial_1. This folder contains SILVA fasta file and a folder named barcode_1. barcode_1 folder contains my sample file barcode_1.fastq
So, from within the directory Trial_1, run the decona command!
