### ISSUE TITLE
support for conda 4.9.2?

### ISSUE THREAD

**Issue by EWisely** [Saskia-Oosterbroek/decona#5]
Hi, I'm trying to install via conda (version 4.9.2) but get the following message "It seems like you have a different version of Conda, please let Saskia know so it can be added!" :-)

**Comment by EWisely** [comment]
It worked perfectly on ubuntu 20.04, just Mac OSX.  Sorry for my confusion.

**Comment by ramongallego** [comment]
I am also trying to run decona on a Mac BigSur - I had the same issue but I don't have an Ubuntu machine - Any ideas on how to install in a Mac with conda4.9.2?
