### ISSUE TITLE
rename: not enough arguments

### ISSUE THREAD

**Issue by leocaserta** [Saskia-Oosterbroek/decona#7]
Hello, 
I tried running decona on a set of 24 fastq files but the program stops and prints the following message:

(decona) [lcc88@cbsumm10 fastq_files]$ decona -l 1000 -m 1800 -q 7 -c 0.80 -n 10 -M -T 24 rename -v
Filtering data NEC.fastq...
Filtering data S1.fastq...
Filtering data S18.fastq...
Filtering data S19.fastq...
Filtering data S2.fastq...
Filtering data S20.fastq...
Filtering data S21.fastq...
Filtering data S22.fastq...
Filtering data S23.fastq...
Filtering data S3.fastq...
Filtering data S38.fastq...
Filtering data S39.fastq...
Filtering data S4.fastq...
Filtering data S40.fastq...
Filtering data S41.fastq...
Filtering data S42.fastq...
Filtering data S5.fastq...
Filtering data S55.fastq...
Filtering data S56.fastq...
Filtering data S57.fastq...
Filtering data S58.fastq...
Filtering data S59.fastq...
Filtering data S6.fastq...
Filtering data S60.fastq...
Data filtered with NanoFilt
Data not demultiplexed
Fastq reads are being transformed to fasta
rename: not enough arguments

Usage:
 rename [options] expression replacement file...

Options:
 -v, --verbose    explain what is being done
 -s, --symlink    act on symlink target

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see rename(1). 

Am i doing something wrong? 

Thank you,
Leonardo

**Comment by Saskia-Oosterbroek** [comment]
Hello Leonardo,

Have you tried running Decona without "rename -v"?
Rename is a program that is used within the Decona tool but is not an option that can be set as such. Your terminal now likely treats them as two different commands. First you give the Decona command which is being run and then the terminal reads a second command "rename -v".
As you are using the -v flag you probably want to know what is actually being renamed. To reassure you, none of your sample or barcode names are being changed. I simply used it to change prefixes and extensions. Example: Sample1.fastq will be renamed to sample1.fasta and consensus_sample1.fasta after certain steps in the program.

I hope this helps!
Kind regards,
Saskia

**Comment by leocaserta** [comment]
Hi Saskia, thank you for your response. 
Actually I have tried with and without "rename -v" and both give me the same message (rename: not enough arguments). 
I've tried many different ways but I still can't make it work. 

Best, 
Leonardo
