### ISSUE TITLE
Install in a Mac using miniconda 4.9.2

### ISSUE THREAD

**Issue by ramongallego** [Saskia-Oosterbroek/decona#8]
I am also trying to run decona on a Mac BigSur - I had the same issue but I don't have an Ubuntu machine - Any ideas on how to install in a Mac with conda4.9.2?

_Originally posted by @ramongallego in https://github.com/Saskia-Oosterbroek/decona/issues/5#issuecomment-812325726_

**Comment by Saskia-Oosterbroek** [comment]
Hello Ramon,

Unfortunately use with Mac is currently not supported. 
It was developed for use with Linux. The Ubuntu terminal app on Windows also works but is only recommended for smaller datasets. 

Saskia

**Comment by ramongallego** [comment]
Hello Saskia,

Thanks for the update - not what I hoped but thanks anyway!

Ramón

**Comment by Saskia-Oosterbroek** [comment]
Hi Ramón!
You may have already tried by now (I was on a holiday). I use Miniconda 3 myself. I didn't know about Google Colab, but that looks pretty useful! I wonder how much space and computing power they allow you to use though.. Let me know if it works :)
Best,
Saskia
